name Logos Acme
type light
base_0 #ffffea
base_1 #f8f8e3
base_2 #f2f2dd
base_3 #e8e8d3
base_4 #ddddc9
base_5 #777770
base_6 #000000
base_7 #000000
red_1 #bb5d5d
red_2 #dd8888
orange_1 #c78f67
orange_2 #f8dfc8
yellow_1 #99884c
yellow_2 #eeee9e
green_1 #558855
green_2 #a8cca8
green_3 #eaffea
cyan_1 #5aaaaa
cyan_2 #8ccccc
blue_1 #4670bb
blue_2 #afdbff
purple_1 #8888cc
purple_2 #bbbbff
magenta_1 #aa6688
magenta_2 #d08eaa
match_1 #eeee9e
match_2 #ccccff
