[base]
background_primary = "{color_base_00}"
background_strong = "{color_base_25}"
background_floating_element = "{color_base_100}alpha(20)"
bold_color = "#000000"
color_bright_black = "{color_base_70}"
text_normal = "{color_base_100}"
text_bold = "{bold_color}"
invisible = "#00000000"

[light]
color_base_05 = "mix({color_base_00},{color_base_100},1.2)"
color_base_10 = "mix({color_base_00},{color_base_100},2)"
color_base_20 = "mix({color_base_00},{color_base_100},3.6)"
color_base_25 = "mix({color_base_00},{color_base_100},6.4)"
color_base_30 = "mix({color_base_00},{color_base_100},10.8)"
color_base_35 = "mix({color_base_00},{color_base_100},14.9)"
color_base_40 = "mix({color_base_00},{color_base_100},27.0)"
color_base_50 = "mix({color_base_00},{color_base_100},34.6)"
color_base_60 = "mix({color_base_00},{color_base_100},60.8)"
color_base_70 = "mix({color_base_00},{color_base_100},70.2)"

background_secondary = "{color_base_20}"
background_secondary_alt = "{color_base_25}"
background_highlight_primary = "{color_bright_orange}alpha(50)"
background_highlight_secondary = "{color_bright_purple}alpha(50)"
background_hover_primary = "{color_base_100}alpha(5)"
background_hover_secondary = "{color_base_100}alpha(10)"
background_bold = "{color_base_70}"
background_raised = "{color_base_00}"
background_selection = "{color_base_100}alpha(9)"
background_drop = "{color_base_30}"

text_muted = "{color_base_100}alpha(70)"
text_dim = "{color_base_100}alpha(50)"
text_faint = "{color_base_100}alpha(30)"
foreground_ghost = "{color_base_100}alpha(9.5)"
link_color = "#708ddb"

border = "{color_base_100}alpha(24)"
border_hard = "{color_base_100}alpha(54)"
border_soft = "{color_base_100}alpha(15)"
border_popup = "{color_base_100}alpha(54)"

color_black = "{color_base_100}"
color_bright_white = "{color_base_00}"
color_red = "#bb5555"
color_bright_red = "#e89090"
color_orange = "#d08868"
color_bright_orange = "#f0c0a0"
color_yellow = "#aa8866"
color_bright_yellow = "#f0d0aa"
color_green = "#889944"
color_bright_green = "#b0c088"
color_blue = "#667799"
color_bright_blue = "#bbc8dd"
color_purple = "#8c6d9c"
color_bright_purple = "#bcc6ff"
color_magenta = "#bb6677"
color_bright_magenta = "#d8b8c8"
color_cyan = "#669988"
color_bright_cyan = "#b8dbd4"

[dark]
color_base_05 = "mix({color_base_00},{color_base_100},1.2)"
color_base_10 = "mix({color_base_00},{color_base_100},2)"
color_base_20 = "mix({color_base_00},{color_base_100},3.6)"
color_base_25 = "mix({color_base_00},{color_base_100},6.4)"
color_base_30 = "mix({color_base_00},{color_base_100},10.8)"
color_base_35 = "mix({color_base_00},{color_base_100},14.9)"
color_base_40 = "mix({color_base_00},{color_base_100},27.0)"
color_base_50 = "mix({color_base_00},{color_base_100},34.6)"
color_base_60 = "mix({color_base_00},{color_base_100},60.8)"
color_base_70 = "mix({color_base_00},{color_base_100},70.2)"

text_muted = "{color_base_100}alpha(72.16)"
text_dim = "{color_base_100}alpha(53.33)"
text_faint = "{color_base_100}alpha(26)"
foreground_ghost = "{color_base_100}alpha(15.69)"
link_color = "{color_cyan}"

background_secondary = "{color_base_30}"
background_secondary_alt = "{color_base_35}"
background_highlight_primary = "{color_magenta}alpha(73.33)"
background_highlight_secondary = "{color_cyan}alpha(73.33)"
background_hover_primary = "{color_base_100}alpha(10)"
background_hover_secondary = "{color_base_100}alpha(20)"
background_bold = "{color_base_100}"
background_raised = "{color_base_30}"
background_selection = "{color_base_100}alpha(18.82)"
background_drop = "{color_base_40}"

border = "{color_base_25}"
border_hard = "{color_base_100}alpha(40.78)"
border_medium = "{color_base_100}alpha(28.24)"
border_soft = "{color_base_100}alpha(15.69)"
border_popup = "{color_base_30}"

color_black = "{color_base_00}"
color_bright_white = "{color_base_100}"
color_red = "#f87870"
color_orange = "#dd9966"
color_yellow = "#eebb88"
color_green = "#aab866"
color_blue = "#80a8b0"
color_purple = "#8c6d9c"
color_magenta = "#d3889b"
color_cyan = "#88b4a0"
color_bright_red = "{color_red}"
color_bright_orange = "{color_orange}"
color_bright_yellow = "{color_yellow}"
color_bright_green = "{color_green}"
color_bright_blue = "{color_blue}"
color_bright_purple = "{color_purple}"
color_bright_magenta = "{color_magenta}"
color_bright_cyan = "{color_cyan}"

[palettes.logos]
name = "Logos"
type = "light"
color_base_00 = "#ffffff"
color_base_100 = "#222222"

[palettes.logos-acme]
name = "Logos Acme"
type = "light"
color_base_00 = "#ffffea"
color_base_100 = "#000000"
background_highlight_primary = "#eeee9e"
background_highlight_secondary = "#ccccff"
color_blue = "#4670bb"
color_cyan = "#5aaaaa"
color_green = "#558855"
color_magenta = "#aa6688"
color_orange = "#c78f67"
color_purple = "#8888cc"
color_red = "#bb5d5d"
color_yellow = "#99884c"
color_bright_blue = "#afdbff"
color_bright_cyan = "#8ccccc"
color_bright_green = "#a8cca8"
color_bright_magenta = "#d08eaa"
color_bright_orange = "#f8dfc8"
color_bright_purple = "#bbbbff"
color_bright_red = "#dd8888"
color_bright_yellow = "#eeee9e"

[palettes.logos-blue]
name = "Logos Blue"
type = "dark"
color_base_00 = "#405898"
color_base_100 = "#ffffff"
color_red = "#dd7880"
color_green = "#aaccbb"
color_blue = "#a0c0e0"
color_yellow = "#ddbb99"
color_magenta = "#b48ead"
color_cyan = "#88c0d0"
bold_color = "#ffffff"

[palettes.logos-dark]
name = "Logos Dark"
type = "dark"
color_base_00 = "#282828"
color_base_100 = "#d8d8d8"
bold_color = "#ffffff"

[palettes.logos-gruv]
name = "Logos Gruv"
type = "dark"
color_base_00 = "#302d2c"
color_base_100 = "#eed8c2"
bold_color = "#ffefcc"

[palettes.logos-paper]
name = "Logos Paper"
type = "light"
color_base_00 = "#faf7f2"
color_base_100 = "#403a32"
bold_color = "#000000"

[palettes.logos-sun]
name = "Logos Sun"
type = "light"
color_base_00 = "#fffffa"
color_base_100 = "#000000"
bold_color = "#000000"
background_highlight_primary = "#f8e8bb"
background_highlight_secondary = "#d0d8f0"

[hc_base]
border = "{color_base_70}"
background_selection = "{color_base_60}alpha(87)"

[hc.logos]
include = "./logos-color-theme.json"
name = "Logos High Contrast"
type = "hc-light"

[hc.logos-acme]
include = "./logos-acme-color-theme.json"
name = "Logos Acme High Contrast"
type = "hc-light"

[hc.logos-paper]
include = "./logos-paper-color-theme.json"
name = "Logos Paper High Contrast"
type = "hc-light"

[hc.logos-sun]
include = "./logos-sun-color-theme.json"
name = "Logos Sun High Contrast"
type = "hc-light"
